services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: delivery_center
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./dataset:/dataset
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d delivery_center"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db-network

  etl:
    build: . # busca um Dockerfile no diretório especificado
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./dataset:/app/dataset
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  postgres_data: